version: '3'

services:
  db:
    image: mongo:latest
    volumes:
      - .data/:/data/db
    ports:
      - 27017:27017

  mongo_export:
    image: mongo:latest
    links:
      - db
    volumes:
      - ./reviews:/seed-data
    command:
      'bash mongoexport --db test --collection reviews --out /seed-data/reviews_classified.json'


        #  mongo_seed:
        #    image: mongo:latest
        #    links:
        #      - db
        #    volumes:
        #      - ./reviews:/seed-data
        #    command:
        #      'bash -c "mongoimport --host db --type json --file /seed-data/reviews.json"'
